#!/bin/bash


if [ -x /usr/bin/tput ] && tput setaf 1 >& /dev/null; then
	use_color=t
fi


# Enable color support of ls and also add handy aliases.
if [[ ! -z "$use_color" ]] && [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors \
    && eval "$(dircolors -b ~/.dircolors)" \
      || eval "$(dircolors -b)"

  alias ls='ls --color=auto --classify'

  alias grep='grep --color=auto'
  # alias fgrep='fgrep --color=auto'
  # alias egrep='egrep --color=auto'
fi

# Variations of ls
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alh'

alias open='xdg-open'


# Alias and completion for Git.
if [[ -e /usr/share/bash-completion/completions/git ]]; then
  . /usr/share/bash-completion/completions/git
  __git_complete g __git_main
  __git_complete gco _git_checkout

  alias g='git'
  alias gf='g fetch -p'
  alias gp='g pull'
  alias gco='g checkout'
  alias gst='g status'

  # TODO: Want git push/pull aliased as well, but completion does not
  # appear to work with <repo> [<refspec>] CLI.
fi


# Override command `cd` to source local .bashrc if exists.
function cd() {
  command cd "$@" || return
  local bashrc="$PWD/.bashrc"
  if [[ $PWD != $HOME && -f $bashrc ]]; then
    read -p 'Load directory-specific Bash config? [Y/n]: ' resp
    resp=${resp:-y}
    if [[ $resp == "Y" ]] || [[ $resp == "y" ]]; then
      source $bashrc
      msg="Sourced $bashrc"
      [[ ! -z "$use_color" ]] && msg="\033[0;32m${msg}\033[0m"
      >&2 echo -e "$msg"
    fi
  fi
}
