# -*- mode: sh; sh-basic-offset: 2; -*-

if [ -f ~/github.com/okomestudio/environment/bash-it/aliases/custom.aliases.bash ]; then
  . ~/github.com/okomestudio/environment/bash-it/aliases/custom.aliases.bash
fi
