#!/bin/sh
#
# Add syntax highlighting via Pygments
#
# Install Pygments:
#
#   $ pip install Pygments
#
# and add the following lines to ~/.bashrc:
#
#   export LESS='-R'
#   export LESSOPEN='|~/.lessfilter %s'
#
# and save this file as ~/.lessfilter
#


parse_shebang() {
  line=$(head -n1 $1)
  prog=$(echo "$line" | grep -E '^#!(|/usr)/bin/env' | cut -d " " -f 2)
  if [ -z $prog ]; then
    prog=$(echo "$line" | grep -Po '/bin/\K[^ ]+')
  fi
  echo $prog
}


case $1 in
  *.ad[asb]|\
  *.asm|\
  *.awk|\
  *.axp|\
  *.c|\
  *.cc|\
  *.cpp|\
  *.cxx|\
  *.diff|\
  *.ebuild|\
  *.eclass|\
  *.groff|\
  *.h|\
  *.hh|\
  *.hpp|\
  *.hxx|\
  *.htm|\
  *.html|\
  *.inc|\
  *.java|\
  *.js|\
  *.json|\
  *.l|\
  *.lsp|\
  *.m4|\
  *.md|\
  *.p|\
  *.pas|\
  *.php|\
  *.pl|\
  *.pm|\
  *.pod|\
  *.sh|\
  *.tex|\
  *.xml|\
  *.xps|\
  *.xsl|\
  *.patch|\
  *.pov|\
  *.ppd|\
  *.py|\
  *.rb|\
  *.sql)
    pygmentize -f 256 -O bg=light $1
    ;;
  *.el|\
  .emacs|*/.emacs)
    pygmentize -f 256 -O bg=light -l elisp $1
    ;;
  *.bash|\
  .bashrc|*/.bashrc|\
  .bash_aliases|*/.bash_aliases|\
  .bash_environment|*/.bash_environment)
    pygmentize -f 256 -O bg=light -l bash $1
    ;;
  *)
    prog=$(parse_shebang $1)
    if [ ! -z $prog ]; then
      case $prog in
        python3*)
          pygmentize -f 256 -O bg=light -l python3 $1
          ;;
        python2*)
          pygmentize -f 256 -O bg=light -l python2 $1
          ;;
        bats)
          pygmentize -f 256 -O bg=light -l bash $1
          ;;
        *)
          pygmentize -f 256 -O bg=light -l $prog $1
          ;;
      esac
    fi
    ;;
esac

exit 0
