#!/bin/bash
#
# .xsessionrc for ThinkPad X1 Carbon 5th Gen (2017)

set -e

source .local/include/xsessionrc_helpers.sh

# device_id=$(get_device_id "PS/2 Generic Mouse")
device_id=$(get_device_id "TPPS/2 Elan TrackPoint")
if [[ -n "$device_id" ]]; then
  setp="xinput --set-prop $device_id"
  ${setp} --type=float "libinput Accel Speed" 0.0
  ${setp} "Coordinate Transformation Matrix" \
          6.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 1.0
fi

# device_id=$(get_device_id "SynPS/2 Synaptics TouchPad")
device_id=$(get_device_id "Synaptics TM3289-002")
if [[ -n "$device_id" ]]; then
  setp="xinput --set-prop $device_id"
  # Disable TrackPad.
  ${setp} --type=int "Device Enabled" 1
fi

device_id=$(get_device_id "Logitech MX Ergo")
if [[ -n "$device_id" ]]; then
  setp="xinput --set-prop $device_id"
  ${setp} 'libinput Accel Speed' 0.5
  ${setp} 'Coordinate Transformation Matrix' 0.5 0 0 0 0.5 0 0 0 .3
fi
