#!/bin/bash
#
# Evoluent VM4S Vertical Mouse 4

set -e

source .local/include/xsessionrc_helpers.sh

device_id=$(get_device_id "Evoluent VerticalMouse 4")
if [[ -n "$device_id" ]]; then
  xinput --set-button-map "$device_id" 1 3 2 4 5 6 7 8 10 9 11 12 13 14
fi
