#!/usr/bin/env bash

set -e


function usage() {
  cat <<USAGE
Postman installer

See getpostman.com for detail.

USAGE
  exit ${1:-1}
}


function error() {
  >&2 echo "ERROR: $1"
  exit ${2:-1}
}


function get_prefix() {
  if [[ $USER == root ]]; then
    echo "/usr/local"
  else
    echo "~/.local"
  fi
}


function main() {
  local src=${1:-https://dl.pstmn.io/download/latest/linux?arch=64}
  local dest=$(get_prefix)
  [[ -z $dest ]] && error "Cannot define installation target"
  
  local libdir="${dest}/postman"

  if ! mkdir -p "$libdir" &> /dev/null ; then
    error "$libdir cannot be created"
  fi

  if [[ ! -w "$libdir" ]]; then
    error "$libdir is not accessible"
  fi

  [[ -e "${dest}/bin/Postman" ]] && rm "${dest}/bin/Postman"
  [[ -d "${libdir}.bk" ]] && rm -rf "${libdir}.bk"
  [[ -d "${libdir}" ]] && mv "${libdir}" "${libdir}.bk"
  mkdir -p "$libdir"

  if ! ls /tmp/Postman-*.tar.gz &> /dev/null ; then
    wget --content-disposition -P /tmp/ "$src"
  fi
  tar -C "$libdir" --strip-components=1 -xvzf /tmp/Postman-*.tar.gz
  ln -s "$libdir/Postman" "${dest}/bin/Postman"
  
  rm /tmp/Postman-*.tar.gz
}


while getopts hu opt; do
  case $opt in
    h)
      usage 0
      ;;
    \?)
      usage
      ;;
  esac
done
shift $(($OPTIND - 1))

main "$@"
