#!/usr/bin/env bash

# apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev
# see: https://github.com/pyenv/pyenv/wiki


function upinst() {
  if command -v pyenv 1>/dev/null 2>&1; then
    pyenv update
  else
    url=https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    curl -L $url | bash
  fi
}


function update_bashrc() {
  local target=~/.bashrc
  local firstline="# pyenv"
  local l=$'\n'"$firstline"$'\n'
  l="${l}if [[ -d ~/.pyenv ]]; then"$'\n'
  l="${l}  if [[ \":\$PATH:\" != *\":~/.pyenv/bin:\"* ]]; then"$'\n'
  l="${l}    export PATH=\"~/.pyenv/bin:\$PATH\""$'\n'
  l="${l}  fi"$'\n'
  l="${l}  if command -v pyenv 1>/dev/null 2>&1; then"$'\n'
  l="${l}    eval \"\$(pyenv init - --no-rehash bash)\""$'\n'
  l="${l}    eval \"\$(pyenv virtualenv-init - --no-rehash bash)\""$'\n'
  l="${l}  fi"$'\n'
  l="${l}fi"$'\n'
  if ! grep -Fxq "$firstline" $target ; then
    echo -e "$l" >> $target
  fi
}


upinst
update_bashrc
