#!/usr/bin/env bash
#
# Install an alternative version of Python
#
# Reference
# ---------
#
#   https://unix.stackexchange.com/questions/332641/how-to-install-python-3-6
#

declare -r version=3.7.0

wget https://github.com/python/cpython/releases/tag/v$version

tar xvf Python-3.6.3.tgz
cd Python-3.6.3
./configure --enable-optimizations --with-ensurepip=install --prefix=$HOME/.local
make -j8
make altinstall
