#!/usr/bin/env bash
#
#   $ sudo ./installer/docker
#

readonly osid=$(. /etc/os-release; echo "$ID")
readonly release=$(lsb_release -cs)
readonly sourcefile=/etc/apt/sources.list.d/docker.list
readonly repo=https://download.docker.com/linux/debian


function add_to_apt_keyring() {
  curl -fsSL https://download.docker.com/linux/$osid/gpg \
    | apt-key add -
}


function update_source_list() {
  local line="deb [arch=amd64] $repo $release stable"
  local target=$sourcefile
  touch $target
  if ! grep -Fxq "$line" $target ; then
    echo -e "\n$line" >> $target
  fi
}


function main() {
  add_to_apt_keyring
  update_source_list

  apt-get update
  apt-get install docker-ce
}


main "$@"
