#!/bin/bash
#
# ``Postman`` installer
#
# See getpostman.com for detail.
#

set -e

declare src=https://dl.pstmn.io/download/latest/linux?arch=64
declare dest=/usr/local


function install() {
  declare src=$1
  declare dest=$2
  declare libdir="${dest}/postman"

  if ! mkdir -p "$libdir" &> /dev/null ; then
    echo "ERROR: ${libdir} cannot be created"
    return 1
  fi

  if [[ ! -w "$libdir" ]]; then
    echo "ERROR: ${libdir} is not accessible"
    return 1
  fi

  [[ -e "${dest}/bin/Postman" ]] && rm "${dest}/bin/Postman"
  [[ -d "${libdir}.bk" ]] && rm -rf "${libdir}.bk"
  [[ -d "${libdir}" ]] && mv "${libdir}" "${libdir}.bk"
  mkdir -p "$libdir"

  if ! ls /tmp/Postman-*.tar.gz &> /dev/null ; then
    wget --content-disposition -P /tmp/ "$src"
  fi
  tar -C "$libdir" --strip-components=1 -xvzf /tmp/Postman-*.tar.gz
  ln -s "$libdir/Postman" "${dest}/bin/Postman"
  
  rm /tmp/Postman-*.tar.gz
}


function usage() {
  echo ""
  echo "usage: install_postman [-u]"
  echo ""
  echo "       -u  Install locally for the current user"
  echo ""
  exit 1
}


while getopts hu opt; do
  case $opt in
    u) dest=~/.local
       ;;
    h) usage
       ;;
    \?) usage
        ;;
  esac
done

install "$src" "$dest"
