#!/bin/bash
#
# ``arcanist`` is a command-line utility for Phabricator.
#

set -e


function install() {
  sudo apt-get install arcanist
}


function configure() {
  declare url=$1
  arc set-config default "$url"
  arc install-certificate
}


function usage() {
  echo ""
  echo "usage: install_arcanist [phaburl]"
  echo ""
  echo "       -h  Help"
  echo ""
}


while getopts "h" opt; do
  case $opt in
    h)
      usage
      exit 1
      ;;
    \?)
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done


declare phaburl=$1

install

if [[ -n "$phaburl" ]]; then
  configure "$phaburl"
fi
