#!/bin/bash
#
# ``xflux`` is a utility for adjusting display color based on time
#
# See: https://justgetflux.com/
#

set -e

declare src=https://justgetflux.com/linux/xflux64.tgz
declare dest=/usr/local
declare cmd=xflux


function install() {
  declare src=$1
  declare dest=$2
  if [[ (! -d "$dest") || (! -w "$dest") ]]; then
    echo "ERROR: $dest is not a directory or is not accessible"
    return 1
  fi

  declare tmpfile=$(mktemp /tmp/${cmd}.XXXXXX)

  wget -O "$tmpfile" "$src" && \
    tar -C "$dest/" -xvf "$tmpfile" && \
    chmod +x "$dest/$cmd" || \
      echo "ERROR: Could not finish installation"

  rm "$tmpfile"
}


function usage() {
  echo ""
  echo "usage: install_${cmd} [-u]"
  echo ""
  echo "       -d  Autostart a daemon with given zip code"
  echo "       -f  Force reinstallation of binary"
  echo "       -h  Help"
  echo "       -u  Install locally for the current user"
  echo ""
  exit 1
}


while getopts "d:fhu" opt; do
  case $opt in
    d)
      zipcode="$OPTARG"
      ;;
    f)
      force=1
      ;;
    h)
      usage
      ;;
    u)
      dest=~/.local
      ;;
    \?)
      usage
      ;;
  esac
done


if ! hash "$cmd" 2> /dev/null || [[ -n "$force" ]]; then
  install "$src" "$dest/bin"
fi


if [[ -n "$zipcode" ]]; then
  mkdir -p ~/.kde4/Autostart
  echo "xflux -z ${zipcode}" > ~/.kde4/Autostart/start_xflux
  chmod +x ~/.kde4/Autostart/start_xflux
fi
