#!/bin/bash


echo "deb http://download.virtualbox.org/virtualbox/debian stretch contrib" |
  sudo tee /etc/apt/sources.list.d/virtualbox.list

curl -O https://www.virtualbox.org/download/oracle_vbox_2016.asc
sudo apt-key add oracle_vbox_2016.asc

sudo apt-get update
sudo apt-get install -y virtualbox-5.1 dkms
